// Types for AI Generate Questions API (/ai/generate-questions/{subjectId})

// Context for a group of questions (reading passage, etc.)
export interface AIGeneratedContext {
    title: string;
    content: string;
    imageUrl?: string;
    audioUrl?: string;
    subjectId: string;
}

// Answer option for a question
export interface AIGeneratedAnswer {
    content: string;
    isCorrect: boolean;
    explanation?: string;
}

// Single question generated by AI
export interface AIGeneratedQuestion {
    context?: AIGeneratedContext;
    contextId?: string;
    content: string;
    type: "MCQ" | "FRQ";
    subjectId: string;
    difficultyName: string;
    topicName: string;
    answers: AIGeneratedAnswer[];
    imageUrl?: string;
    audioUrl?: string;
}

// Response from AI generate questions API
export interface AIGenerateQuestionsResponse {
    code: number;
    message: string;
    data: AIGeneratedQuestion[];
}

// Request type for batch create (same structure as AIGeneratedQuestion)
export type BatchCreateQuestionRequest = AIGeneratedQuestion;

// Response from batch create API
export interface BatchCreateQuestionsResponse {
    code: number;
    message: string;
    data: {
        id: string;
        content: string;
        type: string;
        subject: {
            id: string;
            name: string;
            description: string;
        };
        difficulty: {
            id: string;
            name: string;
            description: string;
        };
        topic: string;
        answers: {
            id: string;
            content: string;
            isCorrect: boolean;
            explanation?: string;
        }[];
    }[];
}
